<?php

namespace tests\phpsap\classes\helper;

use phpsap\classes\Config\AbstractConfiguration;
use phpsap\interfaces\Config\IConfiguration;

/**
 * Class tests\phpsap\classes\helper\AbstractConfigurationInstance
 *
 * AbstractConfiguration instance where all protected methods are made public for
 * testing.
 *
 * @package tests\phpsap\classes\helper
 * @author  Gregor J.
 * @license MIT
 */
class AbstractConfigurationInstance extends AbstractConfiguration
{
    /**
     * @var array Valid config keys for testing.
     */
    public static $validConfigKeys = ['zadgcjmt'];

    /**
     * Retrieves a configuration value for a given key.
     * @param string $key
     * @return string|int
     * @throws LogicException In case of an invalid configuration key.
     * @throws ConfigKeyNotFoundException In case the key doesn't exist for the
     *                                    current SAP configuration type.
     */
    public function get($key)
    {
        return parent::get($key); // TODO: Change the autogenerated stub
    }

    /**
     * Sets a configuration value for a given key.
     * @param string     $key
     * @param string|int $value
     * @return IConfiguration
     * @throws LogicException In case of an invalid configuration key.
     * @throws InvalidArgumentException In case of an invalid configuration value.
     */
    public function set($key, $value)
    {
        return parent::set($key, $value); // TODO: Change the autogenerated stub
    }

    /**
     * Removes a configuration value for a given key.
     * @param string $key
     * @return IConfiguration
     * @throws LogicException In case of an invalid configuration key.
     */
    public function remove($key)
    {
        return parent::remove($key); // TODO: Change the autogenerated stub
    }

    /**
     * Returns true if the configuration has a value for the given key.
     * @param string $key
     * @return bool
     * @throws LogicException In case of an invalid configuration key.
     */
    public function has($key)
    {
        return parent::has($key); // TODO: Change the autogenerated stub
    }

    /**
     * Get an array of all valid configuration keys and whether they are mandatory.
     * @return array
     */
    public static function getValidConfigKeys()
    {
        return static::$validConfigKeys;
    }

    /**
     * Test set() function.
     * @param $value
     * @return $this
     */
    public function setZadgcjmt($value)
    {
        $this->set('zadgcjmt', $value);
        return $this;
    }
}
